"""empty message

Revision ID: 1abf09fbb38e
Revises: None
Create Date: 2016-12-16 16:31:39.328307

"""

# revision identifiers, used by Alembic.
revision = '1abf09fbb38e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secex_2016_exp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co_ano', sa.String(), nullable=True),
    sa.Column('co_mes', sa.String(), nullable=True),
    sa.Column('co_sh4', sa.String(), nullable=True),
    sa.Column('co_pais', sa.String(), nullable=True),
    sa.Column('co_uf', sa.String(), nullable=True),
    sa.Column('co_porto', sa.String(), nullable=True),
    sa.Column('co_mun_geo', sa.String(), nullable=True),
    sa.Column('kg_liquido', sa.BigInteger(), nullable=True),
    sa.Column('vl_fob', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secex_2016_exp')
    op.drop_table('product')
    ### end Alembic commands ###
