"""empty message

Revision ID: 1e15e6007a89
Revises: None
Create Date: 2016-12-15 16:34:24.283727

"""

# revision identifiers, used by Alembic.
revision = '1e15e6007a89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    ### end Alembic commands ###
